### PR TITLE
Updated for Forge 1.12

### PR DESCRIPTION
**Pull request by Hexeption**

### CODE REVIEW

File: src/main/java/cpw/mods/retro/WorldRetrogen.java [hunk 1]
```diff
@@ -61,18 +53,13 @@
...
-import java.util.Map;
+import java.util.*;
 import java.util.Map.Entry;
-import java.util.Random;
-import java.util.Set;
 import java.util.concurrent.ConcurrentMap;
 import java.util.concurrent.Semaphore;
 
-@Mod(modid="simpleretrogen", name="Simple Retrogen", acceptableRemoteVersions="*", acceptedMinecraftVersions = "[1.9,1.11)")
+@Mod(modid="simpleretrogen", name="Simple Retrogen", acceptableRemoteVersions="*", acceptedMinecraftVersions = "[1.9,1.12]")
```
Comment (Landmaster) [inline src/main/java/cpw/mods/retro/WorldRetrogen.java]: The `acceptedMinecraftVersions` string should be `[1.9,1.13)`, not `[1.9,1.12)` if this is going to support 1.12.

Comment (Landmaster) [inline src/main/java/cpw/mods/retro/WorldRetrogen.java]: For consistency and to handle subversions of 1.12, the `acceptedMinecraftVersions` string should probably be set to `[1.9,1.13)`.

Comment (Landmaster) [inline src/main/java/cpw/mods/retro/WorldRetrogen.java]: This will not work with Minecraft 1.12.1; `acceptedMinecraftVersions` should be `[1.9,1.13)`, not`[1.9,1.12]` .

**Review by Landmaster — CHANGES_REQUESTED** [review]

File: src/main/java/cpw/mods/retro/WorldRetrogen.java [hunk 2]
```diff
@@ -61,18 +53,13 @@
...
-import java.util.Map;
+import java.util.*;
 import java.util.Map.Entry;
-import java.util.Random;
-import java.util.Set;
 import java.util.concurrent.ConcurrentMap;
 import java.util.concurrent.Semaphore;
 
-@Mod(modid="simpleretrogen", name="Simple Retrogen", acceptableRemoteVersions="*", acceptedMinecraftVersions = "[1.9,1.11)")
+@Mod(modid="simpleretrogen", name="Simple Retrogen", acceptableRemoteVersions="*", acceptedMinecraftVersions = "[1.9,1.13]")
```
Comment (Landmaster) [inline src/main/java/cpw/mods/retro/WorldRetrogen.java]: You forgot to change the `]` back to a `)`, since 1.13 is not targeted (i.e. the upper bound is exclusive).

**Review by Landmaster — CHANGES_REQUESTED** [review]

**Review by Landmaster — APPROVED** [review]

**Comment by Landmaster** [comment]
@cpw ETA on merging this?

**Comment by Sukasa** [comment]
This just fails with a number of compilation errors; are there changes to the build config also required?
